spring:
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: http://localhost:8081
          predicates:
            - Path=/members/**
        - id: permission-service
          uri: http://localhost:8082
          predicates:
            - Path=/permissions/**
        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/products/**
