server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/members/**
        - id: permission-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/permissions/**
        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/products/**
